name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - master # or main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node (for GitHub Pages support)
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Upload static site to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web # <- use your Flutter Web build output folder
